name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit private/_tests_
